### ISSUE TITLE
Advanced options - Revoking the PGP Key doesn't give the user feedback

### ISSUE THREAD

**Issue by bbusenius** [hahnicity/megthunderbird#11]

**Comment by JoshuaLyle** [comment]
Do you mean the symmetric key? As in the DEBUGGING button?

Or do you mean revoking the key on the phone doesn't tell the user anything in thunderbird?

**Comment by bbusenius** [comment]
Oops! No, this is a bug for the Android app. It happens when the user clicks on the "Revoke PGP Key" button. I'll reopen this on the Android app. Sorry for the confusion.

**Comment by bbusenius** [comment]
[It looks like I already opened it there](https://github.com/Argonne-National-Laboratory/MEGAndroid/issues/7)
